name: dotnet build exemplo

on:
  push:
    branches: 
      - main   # Define a branch desejada para acionar o workflow
  schedule:
    - cron: '0 * * * *'  # Executar a cada hora


jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: checkout.  # Action pré-existente
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.18

      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
    
  task_demo:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action pré-existente

      - name: Execute custom script
        run: |
          echo "Running scheduled task"
          node scripts/task-demo.js  # Script personalizado
                  
        
            